CUDA_VISIBLE_DEVICES=4 python run_experiment_L.py \
--experiment_folder experiments_test/sbt_bigger_embedding_spade_after_spatial_embedding_auto_adjust_size_with_DA \
--checkpoint_file experiments_train/sbt_bigger_embedding_spade_after_spatial_embedding_auto_adjust_size_with_DA/039_checkpoint.bin \
--test
