CUDA_VISIBLE_DEVICES=0 python run_experiment_L.py \
--experiment_folder experiments_train/sbt_bigger_embedding_spade1234fused_after_spatial_embedding_auto_adjust_size_with_DA_test2 \
# --experiment_folder experiments_train/4_6test_noda \

